# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven
env:
  ALLURE_VERSION: "2.10.0"
  SUREFIRE_ARGS: "--add-opens java.base/java.lang=ALL-UNNAMED"
  SUREFIRE_ARGS_BDD: "--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED  --add-opens=java.desktop/java.awt.font=ALL-UNNAMED"
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types:
      - webhook

jobs:
  build:
    name: Tests on JDK
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        java: [ 8, 11, 13, 14, 15, 17, 18 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          java-package: jdk

      - name: Set parameters for AspectJ
        id: aspect_j_params
        if: ${{ matrix.java > 15 }}
        run: |
          echo "ASPECT_ARGS=-Daspectj.args="\"$SUREFIRE_ARGS\" >> $GITHUB_ENV

      - name: Set parameters for AspectJ
        id: aspect_j_params_empty
        if: ${{ matrix.java < 16 }}
        run: |
          echo "ASPECT_ARGS=-Daspectj.args=''" >> $GITHUB_ENV

      - name: Tests
        id: functests
        timeout-minutes: 10
        if: github.event_name == 'pull_request' && success()
        run: mvn test -ntp ${{ env.ASPECT_ARGS }} --fail-at-end

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        if: github.event_name == 'pull_request' && always()
        with:
          allure_results: target/allure-results
          allure_report: target/allure-report
          allure_history: allure-history

      - name: Check tests are passed
      if: ${{ steps.functests.outcome != 'success' }}
      run: |
        echo Tests result: ${{ steps.functests.outcome }}
        exit 1